image: node:8

stages:
  - test
  - deploy

before_script:
  - npm install

test:
  script:
  - npm test
  artifacts:
    paths:
      - coverage/
    reports:
      junit:
        - '*/test-results.xml'


cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master